name: auto_subtitle
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ffmpeg_kit_flutter_full: ^4.5.1
  file_picker: ^5.0.1
  path_provider: ^2.0.11
  googleapis_auth: ^1.3.1
  google_speech: ^2.1.1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 17d4710c17f4913137e7ec931f6e71eaef443363
  material_color_generator: ^1.1.0
  url_launcher: ^6.1.5
  settings_ui: ^2.0.2
  google_fonts: ^3.0.1
  toggle_switch: ^2.0.1
  liquid_progress_indicator: ^0.4.0
  flutter_platform_alert: ^0.3.0
  icons_launcher: ^2.0.5
  provider: ^6.0.3
  day_night_switcher: ^0.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:

  uses-material-design: true
  assets:
    - lib/assets/header.png
    - lib/assets/credentials.json

icons_launcher:
  platforms:
    macos:
      enable: true
      image_path: "lib/assets/icon.png"
  image_path: "lib/assets/icon.png"